# Stage 1: Install dependencies and build the app
FROM node:24-alpine AS builder

# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
COPY tsconfig*.json ./
COPY next.config.ts ./
RUN npm install

# Copy source files
COPY . .

# SET ENVIRONMENT VARIABLES **BEFORE** BUILDING
ENV NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=SuperSecretKey
ENV NEXT_PUBLIC_DRONEPORT_EMAIL=droneportgroep5@gmail.com
ENV NEXT_PUBLIC_API_BASE_URL=http://localhost:8080/api
ENV NEXT_PUBLIC_RECAPTCHA_SITE_KEY=SuperSecretKey
ENV RECAPTCHA_SECRET_KEY=SuperSecretKey

# Build the Next.js app (THIS IS WHEN NEXT.JS NEEDS THE ENV VARS)
RUN npm run build

# Stage 2: Run the app
FROM node:24-alpine AS runner

# Set working directory
WORKDIR /app

# Copy built output and node_modules from builder
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/next.config.ts ./
COPY --from=builder /app/tsconfig.json ./


# Expose port
EXPOSE 3000

# Start the application
CMD ["npm", "start"]